#!/usr/bin/ansible-playbook

---
# First the common first time thingies for all machines

- hosts: all
  remote_user: root

  tasks:
  - name: copy the EPEL gpg key
    copy: src={{ item }} dest=/etc/pki/rpm-gpg/{{ item }} owner=root group=root
    with_items:
    - RPM-GPG-KEY-EPEL-7
    - CEPH-KEY
    become: true

  - name: Add EPEL repository
    yum_repository:
      name: epel
      description: EPEL packages
      baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    become: true

  - name: Add Ceph noarch repository
    yum_repository:
      name: ceph-noarch
      description: Ceph noarch packages
      baseurl: https://download.ceph.com/rpm-kraken/el7/noarch
      priority: 2
      gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/CEPH-KEY
    become: true

  - name: Add Ceph binary repository
    yum_repository:
      name: ceph
      description: Ceph packages for $basearch
      baseurl: https://download.ceph.com/rpm-kraken/el7/$basearch
      priority: 2
      gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/CEPH-KEY
    become: true

  - name: install common packages
    yum: name={{ item }} state=latest
    with_items:
    - ntp
    - ntpdate
    - yum-plugin-priorities
    - openssh-server
    - emacs-nox
    become: true

  - name: upgrade all packages
    yum: name=* state=latest update_cache=yes
    become: true

  - name: Adding ceph user called pena
    user: name=pena comment="Pena Penanen"
    become: true

  - name: adding pena to sudoers
    copy: src=pena.sudo dest=/etc/sudoers.d/pena mode=0440 owner=root group=root
    become: true

  - name: creating pena's .ssh
    file: dest=/home/pena/.ssh state=directory owner=pena group=pena mode=0700
    become: true
    become_user: pena
    tags: ssh

  - name: copy sshkey script
    copy: src=authorized_keys.sh dest=/usr/local/sbin/authorized_keys.sh owner=root group=root mode=0755
    become: true
    tags: ssh

# Then more special stuff for groups of machines

- hosts: admin
  remote_user: root

  tasks:
  - name: install admin node packages
    yum: name={{ item }} state=latest
    with_items:
    - graphite-web
    - python-carbon
    - ceph-deploy
    become: true

  - name: copy graphite-web config file
    copy: src=graphite-web.conf dest=/etc/httpd/conf.d/graphite-web.conf
    become: true

  - name: set graphite-web page and runtime lib directory attributes
    file: path="{{ item }}" owner=apache group=apache recurse=yes state=directory
    with_items:
    - /usr/share/graphite/webapp
    - /var/lib/graphite-web
    become: true

  - name: set graphite-web wsgi file attributes
    file: path=/usr/share/graphite/graphite-web.wsgi owner=apache group=apache state=file
    become: true

  - name: copy graphite-web setup script
    copy: src=graphite-web-setup.sh dest=/usr/local/sbin/graphite-web-setup.sh owner=root group=root mode=0755
    become: true

  - name: run graphite-web setup script
    command: /usr/local/sbin/graphite-web-setup.sh creates="/var/lib/graphite-web/provisioned"
    become: true
    become_user: apache

  - name: enable httpd
    service: name=httpd enabled=yes
    become: true

  - name: Pena's passwordless ssh key
    command: ssh-keygen -f ~/.ssh/id_rsa -P '' creates=~/.ssh/id_rsa
    become: true
    become_user: pena
    tags: ssh

  - name: fetch Pena's public key(s)
    command: cat ~/.ssh/id_rsa.pub
    register: ssh_keys
    become: true
    become_user: pena
    tags: ssh

  - name: check keys
    debug: msg="{{ ssh_keys.stdout }}"
    delegate_to: node3
    tags: ssh

  - name: deploy Pena's key(s) on all nodes
    command: /usr/local/sbin/authorized_keys.sh "{{ ssh_keys.stdout }}" creates=/home/pena/.ssh/authorized_keys
    delegate_to: "{{item}}"
    with_items: "{{groups['nodes']}}"
    become: true
    become_user: pena
    tags: ssh

- hosts: all
  remote_user: root

  tasks:
  - name: restart machine
    command: /sbin/shutdown -r +1 "First reboot"
    ignore_errors: true
    become: true
